name: aryabhata
description: Dart library to build, simplify, manipulate and solve mathematical equations.
version: 1.0.0
repository: https://github.com/tejainece/equation

environment:
  sdk: ^3.7.0-209.1.beta

# Add regular dependencies here.
dependencies:
  number_factorization: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  number_factorization:
    path: ../number_factorization
